#!/usr/bin/env python3
"""
merge_databases.py — Merge callsign databases into one unified file.

Combines MASTER.SCP + MASTER.DTA + add_calls.txt into COMBINED.SCP.
Filters to valid callsign format only (strips binary garbage from DTA).

Usage: python3 merge_databases.py [--output COMBINED.SCP]
"""

import argparse
import os
import re
import subprocess
import sys

# Valid callsign: 1-2 letters/digits, then 1-2 digits, then 1-4 letters, optional /suffix
CALLSIGN_RE = re.compile(r'^[A-Z0-9]{1,2}\d{1,2}[A-Z]{1,4}(/[A-Z0-9]+)?$')


def load_scp(path):
    """Load plain text SCP file (one callsign per line, # comments)."""
    calls = set()
    if not os.path.exists(path):
        return calls
    with open(path) as f:
        for line in f:
            line = line.strip().upper()
            if line and not line.startswith('#'):
                if CALLSIGN_RE.match(line):
                    calls.add(line)
    return calls


def load_dta(path):
    """Extract callsigns from binary DTA file using strings."""
    calls = set()
    if not os.path.exists(path):
        return calls
    try:
        result = subprocess.run(['strings', path], capture_output=True, text=True)
        for line in result.stdout.splitlines():
            line = line.strip().upper()
            if CALLSIGN_RE.match(line):
                calls.add(line)
    except Exception as e:
        print(f"Warning: could not read {path}: {e}", file=sys.stderr)
    return calls


def load_add_calls(path):
    """Load supplementary callsign file (one per line, no comments)."""
    calls = set()
    if not os.path.exists(path):
        return calls
    with open(path) as f:
        for line in f:
            line = line.strip().upper()
            if line:
                calls.add(line)
    return calls


def main():
    parser = argparse.ArgumentParser(description='Merge callsign databases')
    parser.add_argument('--scp', default='MASTER.SCP', help='Primary SCP file')
    parser.add_argument('--dta', default='MASTER.DTA', help='Binary DTA file')
    parser.add_argument('--scp2009', default='MASTER_2009.SCP', help='Era-correct 2009 SCP')
    parser.add_argument('--dta2009', default='MASTER_2009.DTA', help='Era-correct 2009 DTA')
    parser.add_argument('--add', default='add_calls.txt', help='Supplementary calls')
    parser.add_argument('--output', default='COMBINED.SCP', help='Output merged file')
    args = parser.parse_args()

    sources = {}
    total = set()

    for name, path, loader in [
        ('MASTER.SCP', args.scp, load_scp),
        ('MASTER.DTA', args.dta, load_dta),
        ('MASTER_2009.SCP', args.scp2009, load_scp),
        ('MASTER_2009.DTA', args.dta2009, load_dta),
        ('add_calls.txt', args.add, load_add_calls),
    ]:
        if os.path.exists(path):
            calls = loader(path)
            sources[name] = calls
            new = calls - total
            total |= calls
            print(f"  {name}: {len(calls):,} calls ({len(new):,} new)", file=sys.stderr)

    print(f"\n  COMBINED: {len(total):,} unique callsigns", file=sys.stderr)

    # Write sorted output
    with open(args.output, 'w') as f:
        f.write(f"# Combined callsign database\n")
        f.write(f"# Generated by merge_databases.py\n")
        f.write(f"# Sources: {', '.join(sources.keys())}\n")
        f.write(f"# Total: {len(total)} unique callsigns\n")
        f.write(f"#\n")
        for call in sorted(total):
            f.write(call + '\n')

    print(f"  Written to: {args.output}", file=sys.stderr)


if __name__ == '__main__':
    main()
